a = max('a', 'B', 'Z')
print(a)
b = min('a', 'B', 'Z')
print(b)
c = max('a', 'b', 'A')
print(c)
d = min('a', 'b', 'Z')
print(d)
import math
e= math.ceil(1.2)
print(e)
f = math.log(16,2)
print(f)
g = math.cos(math.pi)
print(g)